
---
apiVersion: v1
kind: Config
current-context: shoot--kyma--c-937ad69
clusters:
- name: shoot--kyma--c-937ad69
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWM2Z0F3SUJBZ0lRUVFuejY1OHh0RCs2MUsydVNpeDFMakFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TWpFd016QXlNVEkwTlRaYUZ3MHpNakV3TXpBeU1USTBOVFphTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyeG94CnF5QU4rYzdkcHFpVnpUT08vZmt0akV2eElmcnFXQ1orUk1iRTBhZ0dLa2tDZFV5ZTMvRitZcFlyL0xSMnpudWgKeHh0K0djUm1lSlFGVXZYZHozYUVLU09xc1kzNmhWNExjMWFpci9jcDQxem45RHAwSHJ3QVBaZldkN3VRNkFWTgp5QzFmcXAzbFdNNTJZbFNQcms4ZjhvODJkVlBLOWE5RmRTbThFcGFyb3hsZjVFKzhVRG9IU3VST0lQWkNZejRuCjdCL09SLzJCTVMwb1hTbjJIL3BQWHE4MU5Rd0NZRTl2R2l2R3Z6M05HdUNMdHBuNnl2a296TmNkZDIrRzIyUTEKdlhHL1UrNXNQMzg4SzJEMDdWZnlTTml6d3ZKL09jaWFYbXMwdEMrT1NSRFZ3QkZpanFsc2tjVnRQQ09mWmlGWQpLODdBeUFqQkJ1MVpSOEorSFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBYVl3RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRrME0wS2Zsd3hER0Vnb25UR29KdVlXVjUvVXdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUcrSjFScnNpa3lIMjYwdzBRRTBCRXFFakdRMjRVTnZCMkNzeVZlMThEaHhJTzRwNmN1SQo4d2NnWE9pd3BmTDF4dE5hcXJJN1BNNEJJVW1QZTBDb25YMU0xZDNCNFhJNjMzazgvV0JGTElBVHFWZ1d3TnR0ClZ5a3pRZ21rN042TzliSFoxUjZ5cHQzTDRJeU1QanRJTEh1bkJCeW5sQjZ2UjAvaFBkZHJadXBxYVh3ZThtamQKb1hHWW9lT2w2QlRYQUxTWG44WjNyK0dOdVlldE5ZTnlCaENGbUxIdU5VdytETlhUQnhzcHd2YkNNOUQ4NzN4SQo4UmZLSmt3Vm1VcXFaYlFlb3l0VkZsREZiY2tWaUlLVXl4TEdVaURieE9GOVRYazhObmZIQXRYbjgxa1RkYVo2CnNuNTBvQTRBM2JpNHNIOWwwRCtGOVM2MzFpeExXNjVBd1NrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-937ad69.kyma.ondemand.com
contexts:
- name: shoot--kyma--c-937ad69
  context:
    cluster: shoot--kyma--c-937ad69
    user: shoot--kyma--c-937ad69
users:
- name: shoot--kyma--c-937ad69
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
